### ISSUE TITLE
[Non-Functional] Don't commit .idea

### ISSUE THREAD

**Issue by ashans** [dulith-muthu/hackerrank-java#1]
## Issue description
Don't commit `.idea` to repository

## Proposed solution
Add `.idea` to `.gitignore` file

**Comment by dulith-muthu** [comment]
Fixed in https://github.com/dulith-muthu/hackerrank-java/commit/a3e25534b55a009c6f3bd81167d26bd9ddf2d6cf
Thanks 😊
